name: Friends CI

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  build-and-test:
    # Use a macOS runner since iOS builds require Xcode
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Select the Xcode version
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      # Step 3: Cache SPM dependencies to speed up builds
      - name: Cache SPM Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # Step 4: Resolve SPM dependencies
      - name: Resolve SPM Dependencies
        run: xcodebuild -resolvePackageDependencies -project Friends.xcodeproj -scheme Friends

      # Step 5: Install SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

      # Step 6: Run SwiftLint
      - name: Run SwiftLint
        run: swiftlint lint --reporter json > swiftlint.result.json

      # Step 7: Build the project
      - name: Build
        run: |
          xcodebuild clean build \
            -project Friends.xcodeproj \
            -scheme Friends \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            CODE_SIGNING_ALLOWED=NO

      # Step 8: Run unit tests
      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project Friends.xcodeproj \
            -scheme Friends \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            CODE_SIGNING_ALLOWED=NO

      # Step 9: Run UI tests
      - name: Run UI Tests
        run: |
          xcodebuild test \
            -project Friends.xcodeproj \
            -scheme FriendsUITests \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            CODE_SIGNING_ALLOWED=NO
